import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { test } from "node:test";
import { resolve } from "node:path";
import { loadOperationState } from "./lib/operation-state.mjs";

const root = resolve(import.meta.dirname, "..");
const readJson = (name) =>
  JSON.parse(readFileSync(resolve(root, "docs", name), "utf8"));
const status = () =>
  readFileSync(resolve(root, "docs/ROADMAP_STATUS.md"), "utf8");

test("roadmap status is current and internally consistent", () => {
  execFileSync(
    process.execPath,
    ["tools/generate-roadmap-status.mjs", "--check"],
    { cwd: root },
  );
});

test("the roadmap plan is machine-valid", () => {
  const roadmap = readJson("ROADMAP.json");
  const ids = new Set(roadmap.workstreams.map((workstream) => workstream.id));
  assert.equal(
    ids.size,
    roadmap.workstreams.length,
    "workstream ids are unique",
  );

  const gateIds = new Set(roadmap.gates.map((gate) => gate.id));
  for (const workstream of roadmap.workstreams) {
    for (const dependency of workstream.depends)
      assert.ok(
        ids.has(dependency),
        `${workstream.id} depends on known ${dependency}`,
      );
    if (workstream.gate)
      assert.ok(
        gateIds.has(workstream.gate),
        `${workstream.id} names a known gate`,
      );
    assert.ok(workstream.planFile, `${workstream.id} names a plan file`);
  }

  for (const batch of roadmap.batches)
    for (const writer of batch.writers)
      assert.ok(ids.has(writer), `batch ${batch.id} writer ${writer} exists`);

  // No status field may creep into the plan: state is derived, never declared.
  for (const workstream of roadmap.workstreams)
    for (const key of ["status", "state", "progress", "complete", "done"])
      assert.ok(
        !(key in workstream),
        `${workstream.id} must not declare "${key}"; state is derived`,
      );
});

test("every lane with operations is owned, and every capability is mapped", () => {
  const roadmap = readJson("ROADMAP.json");
  const { laneSummary } = loadOperationState({ implementation: root });
  const owned = new Set(
    roadmap.workstreams.flatMap((workstream) => workstream.lanes),
  );
  for (const lane of laneSummary)
    if (lane.count > 0)
      assert.ok(
        owned.has(lane.lane),
        `lane ${lane.lane} has an owning workstream`,
      );

  const ids = new Set(roadmap.workstreams.map((workstream) => workstream.id));
  const capabilities = Object.entries(roadmap.capabilityMap);
  assert.equal(capabilities.length, 21, "FB00-FB20 are all mapped");
  for (const [phase, entry] of capabilities) {
    assert.ok(
      entry.workstreams.length > 0,
      `${phase} maps to at least one workstream`,
    );
    for (const workstream of entry.workstreams)
      assert.ok(ids.has(workstream), `${phase} maps to known ${workstream}`);
  }
});

test("retired lane identifiers are redirected, not silently dropped", () => {
  const roadmap = readJson("ROADMAP.json");
  const retired = roadmap.identifiers.retired;
  const ids = new Set(roadmap.workstreams.map((workstream) => workstream.id));
  for (const [old, replacements] of Object.entries(retired)) {
    assert.ok(replacements.length > 0, `${old} names its replacement`);
    for (const replacement of replacements)
      assert.ok(
        ids.has(replacement),
        `${old} redirects to known ${replacement}`,
      );
  }
  const plan = readFileSync(resolve(root, "docs/ROADMAP.md"), "utf8");
  for (const old of Object.keys(retired))
    assert.ok(
      plan.includes(`\`${old}\``),
      `ROADMAP.md explains retired ${old}`,
    );
});

test("status reports only derived facts and never claims an unapproved gate", () => {
  const text = status();
  const { totals } = loadOperationState({ implementation: root });
  assert.match(
    text,
    new RegExp(
      `\\*\\*${totals.implemented}/${totals.operations}\\*\\* root operations`,
    ),
  );
  assert.match(text, /Generated by tools\/generate-roadmap-status\.mjs/);

  const registry = JSON.parse(
    readFileSync(resolve(root, "docs/GATES.json"), "utf8"),
  );
  const approved = Object.values(registry.gates ?? {}).filter((entry) => {
    const latest = entry.latest ?? entry.runs?.at(-1);
    return latest?.passed && (latest.approvals ?? []).length > 0;
  }).length;
  assert.match(
    text,
    new RegExp(`approval recorded: \\*\\*${approved}/`),
    "approved gate count comes from the registry",
  );
});

test("unscheduled gaps stay visible in both the plan and the status", () => {
  const roadmap = readJson("ROADMAP.json");
  assert.ok(roadmap.unscheduledGaps.length > 0);
  const plan = readFileSync(resolve(root, "docs/ROADMAP.md"), "utf8");
  const text = status();
  for (const gap of roadmap.unscheduledGaps) {
    assert.ok(plan.includes(gap.id), `ROADMAP.md records ${gap.id}`);
    assert.ok(text.includes(gap.id), `status records ${gap.id}`);
  }
});

test("the task board exists and carries the claim protocol", () => {
  const board = resolve(root, "docs/TASK_BOARD.md");
  assert.ok(existsSync(board), "docs/TASK_BOARD.md exists");
  const text = readFileSync(board, "utf8");
  for (const column of [
    "Task",
    "Workstream",
    "Owner",
    "Reviewer",
    "Acceptance",
  ])
    assert.ok(text.includes(column), `board has a ${column} column`);
});
