// Assigns every root GraphQL operation used by the vendored Enatega apps to an
// implementation lane and wave. Output feeds docs/OPERATION_LANES.json and the
// operation coverage gate. Usage:
//   node tools/operation-lanes.mjs <inventory.json> docs/OPERATION_LANES.json
import { readFileSync, writeFileSync } from "node:fs";

// Lane ids are defined in docs/superpowers/plans/2026-10-08-enatega-backend/00-master-plan.md.
const exact = {
  // L0 platform kernel
  metricsGeneral: "L0",
  // L1 identity and sessions
  login: "L1",
  ownerLogin: "L1",
  // ownerLogout is deliberately NOT pinned: only the single-vendor admin calls it
  // (inventory apps: ["svadmin(sv)"]), so the "single-vendor-only => L12" rule
  // below owns it until Wave 5. Pinning it to L1 would schedule a
  // single-vendor-only flow inside the multivendor build.
  riderLogin: "L1",
  restaurantLogin: "L1",
  refreshToken: "L1",
  ownerSession: "L1",
  hasOwnerPermission: "L1",
  resetUserSession: "L1",
  createUser: "L1",
  updateUser: "L1",
  profile: "L1",
  emailExist: "L1",
  phoneExist: "L1",
  sendOtpToEmail: "L1",
  sendOtpToPhoneNumber: "L1",
  verifyOtp: "L1",
  forgotPassword: "L1",
  resetPassword: "L1",
  changePassword: "L1",
  Deactivate: "L1",
  appleAuthNonce: "L1",
  pushToken: "L1",
  saveNotificationTokenWeb: "L1",
  saveRestaurantToken: "L1",
  updateNotificationStatus: "L1",
  staffs: "L1",
  staffsPaginated: "L1",
  createStaff: "L1",
  editStaff: "L1",
  deleteStaff: "L1",
  checkReferralCodeExists: "L12",
  // L2 platform configuration and reference data
  configuration: "L2",
  publicConfiguration: "L2",
  adminConfiguration: "L12",
  getVersions: "L2",
  setVersions: "L2",
  getCountries: "L2",
  getCitiesByCountry: "L2",
  getCountryByIso: "L2",
  cuisines: "L2",
  cuisinesPaginated: "L2",
  createCuisine: "L2",
  editCuisine: "L2",
  deleteCuisine: "L2",
  fetchShopTypes: "L2",
  fetchAllShopTypes: "L2",
  fetchShopTypeByUnique: "L2",
  createShopType: "L2",
  updateShopType: "L2",
  deleteShopType: "L2",
  banners: "L2",
  createBanner: "L2",
  editBanner: "L2",
  deleteBanner: "L2",
  tips: "L2",
  createTipping: "L2",
  editTipping: "L2",
  taxes: "L2",
  createTaxation: "L2",
  editTaxation: "L2",
  zones: "L2",
  zonesPaginated: "L2",
  createZone: "L2",
  editZone: "L2",
  deleteZone: "L2",
  auditLogs: "L2",
  uploadImageToS3: "L2",
  uploadToken: "L2",
  createActivity: "L2",
  saveVerificationsToggle: "L2",
  saveVendorTypeToggle: "L12",
  saveGeneralConfiguration: "L12",
  // L3 vendors, restaurants, catalog and discovery
  vendors: "L3",
  vendorCount: "L3",
  getVendor: "L3",
  createVendor: "L3",
  editVendor: "L3",
  deleteVendor: "L3",
  restaurants: "L3",
  restaurantsPaginated: "L3",
  restaurant: "L3",
  restaurantByOwner: "L3",
  createRestaurant: "L3",
  editRestaurant: "L3",
  duplicateRestaurant: "L3",
  deleteRestaurant: "L3",
  hardDeleteRestaurant: "L3",
  getClonedRestaurants: "L3",
  getClonedRestaurantsPaginated: "L3",
  getStoreDetailsByVendorId: "L3",
  getStoreDetailsByVendorIdPaginated: "L3",
  updateDeliveryBoundsAndLocation: "L3",
  getRestaurantDeliveryZoneInfo: "L3",
  updateRestaurantDelivery: "L3",
  updateDeliveryOptions: "L3",
  updateTimings: "L3",
  updateRestaurantBussinessDetails: "L3",
  toggleStoreAvailability: "L3",
  createCategory: "L3",
  editCategory: "L3",
  deleteCategory: "L3",
  restaurantCategoriesPaginated: "L3",
  subCategories: "L3",
  subCategoriesByParentId: "L3",
  subCategory: "L3",
  createSubCategories: "L3",
  deleteSubCategory: "L3",
  createFood: "L3",
  editFood: "L3",
  deleteFood: "L3",
  updateFoodOutOfStock: "L3",
  createAddons: "L3",
  editAddon: "L3",
  deleteAddon: "L3",
  restaurantAddonsPaginated: "L3",
  createOptions: "L3",
  editOption: "L3",
  deleteOption: "L3",
  restaurantOptionsPaginated: "L3",
  coupons: "L3",
  couponsPaginated: "L3",
  createCoupon: "L3",
  editCoupon: "L3",
  deleteCoupon: "L3",
  restaurantCoupons: "L3",
  restaurantCouponsPaginated: "L3",
  createRestaurantCoupon: "L3",
  editRestaurantCoupon: "L3",
  deleteRestaurantCoupon: "L3",
  nearByRestaurants: "L3",
  nearByRestaurantsPreview: "L3",
  nearByRestaurantsCuisines: "L3",
  mostOrderedRestaurants: "L3",
  recentOrderRestaurants: "L3",
  topRatedVendors: "L3",
  popularItems: "L3",
  popularFoodItems: "L3",
  relatedItems: "L3",
  attachedCuisines: "L3",
  fetchCategoryDetailsByStoreId: "L3",
  fetchCategoryDetailsByStoreIdForMobile: "L3",
  reviews: "L3",
  reviewsByRestaurant: "L3",
  restaurantReviewsPaginated: "L3",
  // L4 customers, addresses, favourites, support
  users: "L4",
  usersPaginated: "L4",
  user: "L4",
  deleteUser: "L4",
  updateUserStatus: "L4",
  updateUserNotes: "L4",
  ordersByUser: "L4",
  createAddress: "L4",
  editAddress: "L4",
  deleteAddress: "L4",
  deleteBulkAddresses: "L4",
  selectAddress: "L4",
  addFavourite: "L4",
  userFavourite: "L4",
  createSupportTicket: "L4",
  getSingleUserSupportTickets: "L4",
  getSingleSupportTicket: "L4",
  getTicketMessages: "L4",
  createMessage: "L4",
  updateSupportTicketStatus: "L4",
  getTicketUsers: "L4",
  getTicketUsersWithLatest: "L4",
  // L5 orders, pricing and order lifecycle
  coupon: "L5",
  placeOrder: "L5",
  orders: "L5",
  order: "L5",
  orderDetails: "L5",
  getUsersActiveOrders: "L5",
  getUsersPastOrders: "L5",
  abortOrder: "L5",
  reviewOrder: "L5",
  restaurantOrders: "L5",
  acceptOrder: "L5",
  cancelOrder: "L5",
  orderPickedUp: "L5",
  muteRing: "L5",
  allOrders: "L5",
  allOrdersPaginated: "L5",
  allOrdersWithoutPagination: "L5",
  ordersByRestId: "L5",
  ordersByRestIdWithoutPagination: "L5",
  orderFilterOptions: "L5",
  updateStatus: "L5",
  subscribePlaceOrder: "L5",
  subscriptionOrder: "L5",
  orderStatusChanged: "L5",
  // L6 dispatch, riders, tracking and chat
  riders: "L6",
  ridersPaginated: "L6",
  rider: "L6",
  ridersByZone: "L6",
  availableRiders: "L6",
  createRider: "L6",
  editRider: "L6",
  deleteRider: "L6",
  toggleAvailablity: "L6",
  updateRiderLocation: "L6",
  updateRiderBussinessDetails: "L6",
  updateRiderLicenseDetails: "L6",
  updateRiderVehicleDetails: "L6",
  updateWorkSchedule: "L6",
  riderOrders: "L6",
  assignOrder: "L6",
  assignRider: "L6",
  updateOrderStatusRider: "L6",
  orderTracking: "L6",
  getActiveOrders: "L6",
  getLiveMonitorData: "L6",
  subscriptionZoneOrders: "L6",
  subscriptionAssignRider: "L6",
  subscriptionDispatcher: "L6",
  subscriptionOrderTracking: "L6",
  subscriptionRiderLocation: "L6",
  riderUpdated: "L6",
  chat: "L6",
  sendChatMessage: "L6",
  subscriptionNewMessage: "L6",
  registerLiveActivitySession: "L6",
  removeLiveActivitySession: "L6",
  // L7 payments, ledger and finance
  earnings: "L7",
  transactionHistory: "L7",
  withdrawRequests: "L7",
  createWithdrawRequest: "L7",
  updateWithdrawReqStatus: "L7",
  riderCurrentWithdrawRequest: "L7",
  storeCurrentWithdrawRequest: "L7",
  riderEarningsGraph: "L7",
  storeEarningsGraph: "L7",
  commissionRate: "L7",
  updateCommission: "L7",
  subscriptionPaymentSuccess: "L12",
  // L8 notifications and provider-backed messaging
  notifications: "L8",
  notificationsPaginated: "L8",
  sendNotificationUser: "L8",
  webNotifications: "L8",
  markWebNotificationsAsRead: "L8",
  // L9 dashboards and analytics
  getDashboardUsers: "L9",
  getDashboardUsersByYear: "L9",
  getDashboardOrdersByType: "L9",
  getDashboardSalesByType: "L9",
  getVendorDashboardStatsCardDetails: "L9",
  getVendorDashboardGrowthDetailsByYear: "L9",
  getRestaurantDashboardOrdersSalesStats: "L9",
  getRestaurantDashboardSalesOrderCountDetailsByYear: "L9",
  getRestaurantDashboardOrderSalesDetailsByPaymentMethod: "L9",
  getDashboardOrderSalesDetailsByPaymentMethod: "L12",
  saveAppConfigurations: "L2",
  mostOrderedRestaurantsPreview: "L3",
  recentOrderRestaurantsPreview: "L3",
  topRatedVendorsPreview: "L3",
};
// Customer web keeps its single-vendor documents under lib/ui/single-vendor and
// lib/api/graphql/single-vendor, which the extractor reports as plain "web".
const singleVendorWeb = new Set([
  "calculateCheckout",
  "couponsbyRestaurant",
  "getAllCategoriesWithSubCategoriesDataSeeAllSingleVendor",
  "getAllSubscriptionPlans",
  "getAllUserCredits",
  "getCategoryItemsSingleVendor",
  "getFavoriteFoodsSingleVendor",
  "getFoodDetails",
  "getLimitedTimeFoodsDeals",
  "getMyReferralCode",
  "getRestaurantCategoriesSingleVendor",
  "getScheduleByDay",
  "getSimilarFoods",
  "getUserCart",
  "getWeeklyFoodsDeals",
  "orderDetailsPage",
  "recentActiveOrder",
  "searchSingleVendorFoods",
  "singleVendorDiscovery",
  "cancelSubscription",
  "clearCart",
  "createSubscription",
  "toggleFavoriteFoodSingleVendor",
  "updateSubscription",
  "updateUserCartCount",
  "userCartData",
]);
for (const name of singleVendorWeb) exact[name] = "L12";
// Configuration save mutations all belong to L2 except single-vendor-only ones above.
const byPattern = [[/^save\w+Configuration$/, "L2"]];
const waveOf = {
  L0: 0,
  L1: 2,
  L2: 2,
  L3: 2,
  L4: 3,
  L5: 3,
  L8: 3,
  L6: 4,
  L7: 4,
  L9: 5,
  L12: 6,
};

const [inventoryPath, outputPath] = process.argv.slice(2);
if (!inventoryPath || !outputPath)
  throw new Error("usage: operation-lanes.mjs <inventory.json> <output.json>");
const inventory = JSON.parse(readFileSync(inventoryPath, "utf8"));
const operations = [];
const unassigned = [];
for (const type of ["query", "mutation", "subscription"])
  for (const [name, apps] of Object.entries(inventory[type])) {
    let lane = exact[name] ?? byPattern.find(([re]) => re.test(name))?.[1];
    // Operations used only by single-vendor code paths go to the gated L12 lane.
    const multivendorApps = apps.filter(
      (a) => !a.includes("(sv)") && a !== "svadmin",
    );
    if (!lane && multivendorApps.length === 0) lane = "L12";
    if (!lane) {
      unassigned.push(`${type}.${name}`);
      continue;
    }
    operations.push({
      type,
      name,
      lane,
      wave: waveOf[lane],
      apps,
      multivendorApps,
    });
  }
if (unassigned.length)
  throw new Error(`Unassigned operations: ${unassigned.join(", ")}`);
const lanes = {};
for (const op of operations)
  (lanes[op.lane] ??= []).push(`${op.type}.${op.name}`);
writeFileSync(
  outputPath,
  JSON.stringify(
    {
      schemaVersion: 1,
      source: "vendor/enatega-ui (six packages, pinned d9eb29e)",
      total: operations.length,
      perLane: Object.fromEntries(
        Object.entries(lanes).map(([k, v]) => [k, v.length]),
      ),
      operations,
    },
    null,
    2,
  ) + "\n",
);
console.log(`assigned ${operations.length} operations`);
